name: Release

on:
  push:
    branches: ["master", "main"]

jobs:
  release:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_PUBLISH}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUBLISH}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
